### Negotiate
GET http://localhost:7071/api/negotiate

### Start clock
POST http://localhost:7071/api/start

{
    "ServerTime":"2021-02-05T21:21:39.324+01:00",
    "CountDown":"00:01:30",
    "Yellow":"00:01:00",
    "Red":"00:00:30",
    "BlinkIfOver":true
}

### Stop clock
GET http://localhost:7071/api/stop

### Send message
POST http://localhost:7071/api/send

Hello world again