### Negotiate
GET {{function-url}}/negotiate
x-functions-key: {{NegotiateKey}}
x-timekeeper-userid: 1234

### Start clock
POST {{function-url}}/start
x-functions-key: {{StartClockKey}}

{
    "ServerTime":"2021-02-05T21:21:39.324+01:00",
    "CountDown":"00:01:30",
    "Yellow":"00:01:00",
    "Red":"00:00:30",
}

### Stop clock
GET {{function-url}}/stop
x-functions-key: {{StopClockKey}}

### Send message
POST {{function-url}}/send
x-functions-key: {{SendMessageKey}}

Hello world again

### Test hack

POST {{function-url}}/send
x-functions-key: aJ5POPrR9cenGtiqaiCrPdVM9apG/LlQ6PMpoz6Bc5952wxkX2NmOw==
x-timekeeper-group-id: 2c9eed82-6b06-4686-92f0-12569c206bbe