### Negotiate
GET {{function-url}}/negotiate
x-functions-key: {{NegotiateKey}}
x-timekeeper-userid: 1234

### Test hack

POST https://mango-mud-074ee9103.azurestaticapps.net/api/send
x-timekeeper-group-id: 91f22496-a644-472b-ab73-cd60bbf4be18

### Check auth

GET {{function-url}}/test

GET https://ashy-beach-08118a103.azurestaticapps.net/api/test